apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - image: sjwoodr/homeassistant-k8s-proxy:latest
          imagePullPolicy: Always
          name: homeassistant
          env:
            - name: TZ
              value: "America/New_York"
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 2Gi
              cpu: 1
      restartPolicy: Always
