apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service.yaml
  - virtualservice.yaml
  - deployment.yaml

# we'll only set the namespace to development if its not already being set
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: notImportantHere
      namespace: homeassistant
    unsetOnly: true
