apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homeassistant
  namespace: homeassistant
spec:
  clusterIP: None
  ports:
  - name: homeassistant
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: homeassistant
